# Gradient


In this assignment, we are going to evaluate gradients of the special circuits with the respect to differentiable parameter

In [ ]:
! pip install pennylane

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 28.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 67.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 5.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.3/48.3 kB 5.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 88.0 MB/s eta 0:00:00
  Attempting uninstall: autograd
    Found existing installation: autograd 1.6.2
    Uninstalling autograd-1.6.2:
      Successfully uninstalled autograd-1.6.2


In [ ]:
import pennylane as qml
from pennylane import numpy as np

In the code cell below, the quantum node is parameterized with {params}

In [ ]:
dev = qml.device('default.qubit', wires=2)

@qml.qnode(dev)
def circuit(params):
    qml.RX(params[0], wires=0)
    qml.RY(params[1], wires=1)
    qml.CNOT(wires=[0, 1])
    qml.PhaseShift(params[2], wires=0)
    return qml.expval(qml.PauliZ(0))

For your first and second graded code you should write a code to evalute gradient with the respect to {params}


First you should initialize your params and specify them as differentiable parameter

use {np.random.rand and requires_grad}, then use {qml.grad} to calculate gradient

In [ ]:
params=np.random.rand(3,requires_grad=True)# enter your code here (First graded code)
dcircuit=qml.grad(circuit)# enter your code here (Second graded code)
dcircuit(params)

array([-7.44734589e-01,  2.77555756e-17,  0.00000000e+00])

In the code cell below, the quantum node is parameterized with {phi,theta}

In [ ]:
dev2 = qml.device('default.qubit', wires=2)

@qml.qnode(dev2)
def circuit2(phi, theta):
    qml.RX(phi[0], wires=0)
    qml.RY(phi[1], wires=1)
    qml.CNOT(wires=[0, 1])
    qml.PhaseShift(theta, wires=0)
    return qml.expval(qml.PauliZ(0))

Now, you should write a code to evalute gradient with the respect to both {phi,theta}

First you should initialize your params and specify them as differentiable parameter

use {requires_grad} (HINT:initial value for phi and theta are as follows)



phi = [0.5,0.1]



theta=[0.2]




then use {qml.grad} to calculate gradient

In [ ]:
# enter your code here
phi=np.array([0.5,0.1],requires_grad=True)# (Third graded code)
theta=np.array(0.2,requires_grad=True)# (Fourth graded)
dcircuit=qml.grad(circuit2)# (Fifth graded code)

In [ ]:
dcircuit(phi,theta)

(array([-4.79425539e-01, -6.93889390e-18]),
 tensor(-3.46944695e-18, requires_grad=True))

Please pay attention to code cells below

In [ ]:
dev3 = qml.device('default.qubit', wires=2)

@qml.qnode(dev3)
def circuit3(params):
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    qml.RX(params[0], wires=0)
    qml.RY(params[1], wires=1)
    qml.CNOT(wires=[0, 1])
    return qml.expval(qml.PauliY(0)), qml.expval(qml.PauliZ(1))

In [ ]:
j1 =qml.jacobian(lambda x: np.stack(circuit3(x)))
j1(params)

array([[-0.05723617, -0.12775281,  0.        ],
       [-0.12775281, -0.05723617,  0.        ]])